/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Controllers.DBConnection;
import Model.SinhVien;
import Model.ThongTinGD;
import Model.ThongTinSV;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class TrangQuanTri extends javax.swing.JFrame {

    /**
     * Creates new form TrangQuanTri
     */
    ArrayList<SinhVien> list = new ArrayList<>();
    DBConnection dbconnection = new DBConnection();
    Connection cnt;
    public TrangQuanTri() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Hệ thống quản lý sinh viên");
        cnt = dbconnection.getConnection();
        loadCSDL();
        loadTable();
        //dung customtable thi tblSinhVien.setModel(new SVCustomTable(list));
    }

    public void loadTable(){
        tblSinhVien.setModel(new SVCustomTable(list));
    }
    public void loadCSDL(){
        ResultSet rs = dbconnection.layThongTinSinhVien();
        try {
            while(rs.next()){
                SinhVien x = new SinhVien();
                x.setMaSV(rs.getString("MASV"));
                x.setTenSV(rs.getString("TENSV"));
                x.setKhoaQL(rs.getString("KHOA"));
                x.setLop(rs.getString("LOP"));
                
                ThongTinSV ttsv = new ThongTinSV();
                ttsv.setNgaySinh(rs.getDate("NGAYSINH").toString());
                ttsv.setSdtSV(rs.getString("SDTSV"));
                ttsv.setEmailSV("EMAILSV");
                ttsv.setQuocTich(rs.getString("NOITHUONGTRU"));
                ttsv.setNoiTamTru(rs.getString("NOITAMTRU"));
                ttsv.setDanToc(rs.getString("DANTOC"));
                ttsv.setDanToc(rs.getString("DANTOC"));
                ttsv.setTonGiao(rs.getString("TONGIAO"));
                ttsv.setSoCCCD("SOCCCD");
                ttsv.setTenNganHang("TENNGANHANG");
                ttsv.setStkNganHang("STKNGANHANG");
                ttsv.setMaBHYT("MABHYT");
                x.setThongTinSV(ttsv);
                
                ThongTinGD ttgd = new ThongTinGD();
                ttgd.setHoTenCha(rs.getString("HOTENCHA"));
                ttgd.setNamSinhCha(rs.getInt("NAMSINHCHA"));
                ttgd.setDienThoaiCha(rs.getString("DIENTHOAICHA"));
                ttgd.setNgheNghiepCha(rs.getString("NGHENGHIEPCHA"));
                ttgd.setDiaChiLienHeCha(rs.getString("DIACHILIENHECHA"));
                ttgd.setHoTenMe(rs.getString("HOTENME"));
                ttgd.setNamSinhMe(rs.getInt("NAMSINHME"));
                ttgd.setDienThoaiMe(rs.getString("DIENTHOAIME"));
                ttgd.setNgheNghiepCha(rs.getString("NGHENGHIEPME"));
                ttgd.setDiaChiLienHeMe(rs.getString("DIACHILIENHEME"));
                ttgd.setHoTenChuHo(rs.getString("HOTENCHUHO"));
                x.setThongTinGD(ttgd);
                
                list.add(x);
            }
            } 
        catch (SQLException ex) {
            Logger.getLogger(TrangQuanTri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSinhVien = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DANH SÁCH SINH VIÊN");

        jLabel2.setText("Mã sinh viên:");

        btnTimKiem.setText("Tìm kiếm");

        tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblSinhVien);

        jMenu1.setText("Nhập mới sinh viên");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Hoạt động");

        jMenuItem1.setText("Quản lý hoạt động");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Xem danh sách khen thưởng");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Kỷ luật");

        jMenuItem3.setText("Quản lý kỷ luật");
        jMenu3.add(jMenuItem3);

        jMenuItem5.setText("Xem danh sách kỷ luật");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Đăng xuất");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabel1)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangQuanTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangQuanTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangQuanTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangQuanTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangQuanTri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblSinhVien;
    private javax.swing.JTextField txtMaSV;
    // End of variables declaration//GEN-END:variables
}
